### ISSUE TITLE
Double open Tag on html element

### ISSUE THREAD

**Issue by ghost** [gemini-hlsw/Scheduler#63]
Not sure why i am getting a double tag on my html element when i tab
![double tag](https://user-images.githubusercontent.com/83230049/152577523-feb7fdc1-beb9-4916-b1aa-6fe3e7e7f1bb.JPG)
?

**Comment by sraaphorst** [comment]
Where is this? I don't believe we have any HTML code in the Scheduler so I'm not sure why you are filing this issue with this project. Are you sure you have the correct project?
